### ISSUE TITLE
Ping Gadi - Meteorpedia is down!

### ISSUE THREAD

**Issue by dandv** [MeteorCommunity/chat#6]
Hey @gadicc - http://www.meteorpedia.com/read/Packaging_existing_Libraries is down

**Comment by gadicc** [comment]
Blah.  Back up.  Thanks.

**Comment by gadicc** [comment]
FYI, there are two issues here:
1. I guess the app is crashing... it's not so well maintained, and still on Meteor 0.5 I think :)  There was a big rewrite planned, but unfortunately all my open source time is going to famous-views now.  It's not off the cards, it's something that's continually bugging me and I'm dying to do (especially since I've thought a lot about the structure etc), just need to find the time.  Also it does currently _work_, mostly :>
2. Nodejitsu don't always notice that it's crashed.  I log in and see that the app is "started" / running, and have to "stop" it and "start" it again.  So I don't get any notification either.  Also been moving to move off nodejitsu but well, it's their free open source hosting and convenient, and stable "most" of the time.

**Comment by physiocoder** [comment]
Down again (400 - www.meteorpedia.com is currently stopped).

**Comment by dandv** [comment]
Down again, for a few days now (!)

@gadicc, now that I work at Google, I've befriended the program manager for [Google Container Engine](https://cloud.google.com/container-engine/). I can get us free hosting for Meteor, on Google's Cloud.

**Comment by gadicc** [comment]
hey, just restarted.  i'm away for the weekend, let's chat more about this next week.  thanks!

**Comment by gadicc** [comment]
@physiocoder thanks for the heads up back then... i managed to restart soon after seeing your message, but was travelling with just a cell phone and crappy 3G, and things flaked after the restart, so please accept my belated thanks :>

@dandv, the big issue is that Meteorpedia is running quite an old release of Meteor... to confess, I'm a bit nervous to touch it after so long, since it's generally working.  There was a big rewrite planned, but then unfortunately all my time for FOSS work went into famous-views.  I haven't given up on the idea, just not sure when I'll have time to work on it properly :(

Beyond that, congrats on the new job!!  That's super exciting, both for you and the apparent attitude towards Meteor there :) :)  As for GCE, quite keen when I have time to experiment hosting Meteor apps in docker containers there.  How are you doing it?

**Comment by dandv** [comment]
Down again. This is quite annoying, as I keep pointing people to http://www.meteorpedia.com/read/Why_Meteor, and who knows how often the site is actually down when I don't look at it.

**Comment by gadicc** [comment]
Sorry, I got it back up as soon as I saw your message - this morning (my time) - but was rushing out and didn't have a chance to respond.

It happens quite rarely, but I agree the situation is annoying and unacceptable.  I'm going to subscribe to a site monitoring service to get quicker alerts (sometimes nodejitsu tells me it's crashed, sometimes it thinks it's still up even though it hasn't), and also work towards tracking down the actual error.  I'll report back here.

**Comment by gadicc** [comment]
uptimerobot.com is now checking meteorpedia.com every 5m, and notifies me to a private email that has alerts on my mobile phone.  haven't given up on trying to solve this / work on the new version, but this will mitigate the damage until it's ready.

**Comment by dandv** [comment]
:+1: How does uptimerobot deal with JS-generated content? Can it tell that Nodejitsu's "page is down" page means Meteorpedia is down? (They probably do send a 404.)

**Comment by gadicc** [comment]
Yeah I also wondered that, actually tested with another site I have at nodejitsu which is intentionally down.  In short, answer is yes... I didn't check all the codes but the "page is down" page is a 400 ("bad request"), and obviously normal is 200.  It's pretty cool actually.

![tmp](https://cloud.githubusercontent.com/assets/381978/6184832/7165e33c-b36f-11e4-8c16-12d19cb8d7df.png)

**Comment by gadicc** [comment]
@dandv, I'm happy to report I found the code that was crashing, and Meteorpedia has had 100% uptime in the 7 days since deploying the fix (vs the 98% since I started monitoring).  So sorry for past downtime but I'm glad this is resolved now until v2 is ready.

**Comment by dandv** [comment]
:+1:

**Comment by dandv** [comment]
Funnily enough, [my user page doesn't load](http://www.meteorpedia.com/read/Dan_Dascalescu). The history appears to be okay, but if I go to http://www.meteorpedia.com/read/Dan_Dascalescu, I get the spinner and this error in the console:

```
undefined
18ee95a37eeba363dccebaaa82e18a7a579d6363.js:1 Exception from Deps recompute function: TypeError: Cannot read property 'content' of undefined
    at S.read2.noLongCode (http://www.meteorpedia.com/18ee95a37eeba363dccebaaa82e18a7a579d6363.js:17:13717)
    at s (http://www.meteorpedia.com/18ee95a37eeba363dccebaaa82e18a7a579d6363.js:10:9574)
    at c (http://www.meteorpedia.com/18ee95a37eeba363dccebaaa82e18a7a579d6363.js:10:9740)
    at http://www.meteorpedia.com/18ee95a37eeba363dccebaaa82e18a7a579d6363.js:10:10612
    at Object.e.labelBranch (http://www.meteorpedia.com/18ee95a37eeba363dccebaaa82e18a7a579d6363.js:9:31478)
    at g (http://www.meteorpedia.com/18ee95a37eeba363dccebaaa82e18a7a579d6363.js:10:10180)
    at http://www.meteorpedia.com/18ee95a37eeba363dccebaaa82e18a7a579d6363.js:10:10585
    at Array.forEach (native)
    at Function.S.each.S.forEach (http://www.meteorpedia.com/18ee95a37eeba363dccebaaa82e18a7a579d6363.js:1:868)
    at u (http://www.meteorpedia.com/18ee95a37eeba363dccebaaa82e18a7a579d6363.js:10:10215)
```

**Comment by gadicc** [comment]
Mmm, I just resaved your page and it seems to be loading ok now.  I hope this isn't since the redeploy, I see that error comes on every initial load now but doesn't seem to stop the site from loading.  Can you confirm?

**Comment by dandv** [comment]
That version worked, but when I restored the latest version I created, the error popped up again. Does my latest version have some Markdown error?

**Comment by gadicc** [comment]
Working now.  There was a bad image link in the meta data that was crashing something.  Can't wait to get rid of this old code but the next version is still some time away :(  And thank god it will be written in the Meteor 1.0 API :P
